// @ts-check
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { SETTINGS, withOverrides } from '../../src/core/settings.js';
import { runRound } from './harness.js';

/**
 * Loads every replay fixture in `tests/sim/replays/` and asserts it still plays back exactly as recorded
 * (`docs/sprints/sprint-02-core-simulation.md` KS-02-06 AC3, `QA-STRATEGY §3`). `tests/sim/replays/README.md`
 * explains the fixture format and why `t` resolves to a tick rather than a wall-clock time.
 *
 * No schema-validation library is used here (`replay.schema.json` is documentation for a human editing a
 * fixture, not a wired-in validator — adding one is a dependency, which needs Opus's sign-off per
 * `CLAUDE.md`); the handful of required fields are checked directly below instead.
 */

const REPLAYS_DIR = dirname(fileURLToPath(import.meta.url)) + '/replays';
const GOLDEN_NO_INPUT_ROUND = join(
  dirname(fileURLToPath(import.meta.url)),
  '../unit/core/__golden__/no-input-round.json',
);

/**
 * A bot that never decides anything. Used only as a placeholder to fix the player count when a replay's own
 * `inputs` — not bot decisions — drive the round (`harness.js`'s `runRound`: bots are ignored once `inputLog`
 * is supplied).
 *
 * @returns {null}
 */
function noopBot() {
  return null;
}

/**
 * @returns {{file: string, replay: object}[]}
 */
function loadReplays() {
  return readdirSync(REPLAYS_DIR)
    .filter((file) => file.endsWith('.json') && file !== 'replay.schema.json')
    .map((file) => ({
      file,
      replay: JSON.parse(readFileSync(join(REPLAYS_DIR, file), 'utf8')),
    }));
}

describe('KS-02-06 replays', () => {
  const replays = loadReplays();

  it('KS-02-06 AC3: at least one replay file exists', () => {
    expect(replays.length).toBeGreaterThan(0);
  });

  it.each(replays)('KS-02-06 AC3: $file has the required replay fields', ({ replay }) => {
    expect(typeof (/** @type {any} */ (replay).seed)).toBe('number');
    expect(Array.isArray(/** @type {any} */ (replay).inputs)).toBe(true);
    expect(Array.isArray(/** @type {any} */ (replay).expectedEvents)).toBe(true);
  });

  it.each(replays)('KS-02-06 AC3: $file replays to exactly its expectedEvents', ({ replay }) => {
    const { seed, settingsOverrides, inputs, expectedEvents } = /** @type {any} */ (replay);
    const settings = settingsOverrides ? withOverrides(settingsOverrides) : SETTINGS;

    const { events } = runRound({ seed, bots: [noopBot, noopBot], settings, inputLog: inputs });

    expect(events).toEqual(expectedEvents);
  });

  it('KS-02-06 AC3: the no-input replay is byte-for-byte the golden no-input round', () => {
    // The golden file (tests/unit/core/__golden__/no-input-round.json) is generated by the merged KS-02-05
    // code; this replay's expectedEvents must be the exact same log (README.md "no-input-round.json"). If
    // they ever disagree, one of the two is wrong — see the README before editing either.
    const golden = JSON.parse(readFileSync(GOLDEN_NO_INPUT_ROUND, 'utf8'));
    const replay = replays.find((entry) => entry.file === 'no-input-round.json');
    expect(replay).toBeDefined();
    expect(/** @type {any} */ (replay).replay.expectedEvents).toEqual(golden);
  });
});
