// @ts-check

/**
 * KI-17-01 — turn Stryker's JSON report into the committed Markdown one.
 *
 * The mutation run's own output is a 3 MB HTML page and a JSON file the size of `src/core` several times
 * over, neither of which belongs in git. What the sprint asks to be committed is much smaller and much more
 * useful: **the score, and every surviving mutant with its file and line**. That list is the working
 * document for KI-17-02 (kill them or explain them), and a diff of it between two runs is how a reviewer
 * sees that a change to `src/core` left a rule unproven.
 *
 * This is deliberately a reader, not a second source of truth. It computes nothing Stryker did not already
 * decide — the score arithmetic below is the one from the mutation-testing-elements schema, restated here
 * only because the JSON stores per-mutant statuses rather than a total.
 *
 * Usage:
 *   node scripts/mutation-report.mjs [--in reports/mutation/mutation.json]
 *                                    [--out docs/qa/playtests/mutation-baseline.md]
 *                                    [--title "..."] [--scope src/core]
 *
 * With no `--out` it writes to stdout, which is what the nightly gate uses to put the survivor list into a
 * job summary without touching a committed file.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * A mutant counts towards the score only if the run actually learned something from it. `Ignored` mutants
 * (excluded by configuration) and `CompileError` mutants (the mutation produced code that cannot run, so no
 * test could ever have caught it) are not evidence either way, and the schema excludes them from the
 * denominator. `NoCoverage` very much is evidence: no test executed the line at all.
 */
const DETECTED = new Set(['Killed', 'Timeout']);
const UNDETECTED = new Set(['Survived', 'NoCoverage']);

/** @param {string[]} argv */
function parseArgs(argv) {
  /** @type {Record<string, string>} */
  const args = {};
  for (let i = 0; i < argv.length; i += 2) {
    if (!argv[i].startsWith('--')) throw new Error(`Unexpected argument: ${argv[i]}`);
    args[argv[i].slice(2)] = argv[i + 1];
  }
  return args;
}

/**
 * @param {{files: Record<string, {mutants: Array<{mutatorName: string, replacement?: string, status: string, location: {start: {line: number, column: number}}}>}>}} report
 */
export function summarise(report) {
  const files = Object.entries(report.files ?? {})
    .map(([path, file]) => {
      const counts = /** @type {Record<string, number>} */ ({});
      for (const mutant of file.mutants) counts[mutant.status] = (counts[mutant.status] ?? 0) + 1;
      const detected = [...DETECTED].reduce((n, s) => n + (counts[s] ?? 0), 0);
      const undetected = [...UNDETECTED].reduce((n, s) => n + (counts[s] ?? 0), 0);
      const valid = detected + undetected;
      return {
        path,
        counts,
        detected,
        undetected,
        valid,
        // A file with no valid mutants has no score rather than a score of 100 — saying 100 % about nothing
        // measured is exactly the kind of green-but-empty signal this whole sprint exists to remove.
        score: valid === 0 ? null : (detected / valid) * 100,
        survivors: file.mutants
          .filter((m) => UNDETECTED.has(m.status))
          .sort((a, b) => a.location.start.line - b.location.start.line),
      };
    })
    .sort((a, b) => (a.score ?? 101) - (b.score ?? 101) || a.path.localeCompare(b.path));

  const detected = files.reduce((n, f) => n + f.detected, 0);
  const undetected = files.reduce((n, f) => n + f.undetected, 0);
  const valid = detected + undetected;
  return {
    files,
    detected,
    undetected,
    valid,
    score: valid === 0 ? null : (detected / valid) * 100,
  };
}

/** @param {number | null} score */
const pct = (score) => (score === null ? '—' : `${score.toFixed(2)} %`);

/**
 * @param {ReturnType<typeof summarise>} summary
 * @param {{title: string, scope: string}} meta
 */
export function renderMarkdown(summary, meta) {
  const lines = [`# ${meta.title}`, ''];
  lines.push(
    `Generated by \`node scripts/mutation-report.mjs\` from \`reports/mutation/mutation.json\`.`,
    `Scope: \`${meta.scope}\`. Run it with \`npm run test:mutation\`.`,
    '',
    `**Mutation score: ${pct(summary.score)}** — ${summary.detected} of ${summary.valid} mutants detected, ` +
      `${summary.undetected} undetected.`,
    '',
    '## Per file',
    '',
    '| File | Score | Killed | Timeout | Survived | No coverage |',
    '|---|---|---|---|---|---|',
  );
  for (const f of summary.files) {
    lines.push(
      `| \`${f.path}\` | ${pct(f.score)} | ${f.counts.Killed ?? 0} | ${f.counts.Timeout ?? 0} | ` +
        `${f.counts.Survived ?? 0} | ${f.counts.NoCoverage ?? 0} |`,
    );
  }

  lines.push('', '## Surviving mutants', '');
  if (summary.undetected === 0) {
    lines.push('None. Every mutant in scope was detected by a test.');
  } else {
    lines.push(
      'Every mutant below is a change to `src/core` that no test noticed. Each one is either killed by a',
      'new assertion or listed in the triage file with a reason it cannot change behaviour (KI-17-02).',
      '',
    );
    for (const f of summary.files) {
      if (f.survivors.length === 0) continue;
      lines.push(`### \`${f.path}\` — ${f.survivors.length}`, '');
      lines.push('| Line | Mutator | Status | Replacement |', '|---|---|---|---|');
      for (const m of f.survivors) {
        // Replacements are source text and routinely contain a pipe or a newline; both would break the row.
        const replacement = (m.replacement ?? '').replace(/\s+/g, ' ').trim();
        const cell = replacement.length > 90 ? `${replacement.slice(0, 87)}…` : replacement;
        lines.push(
          `| ${m.location.start.line} | ${m.mutatorName} | ${m.status} | \`${cell.replaceAll('|', '\\|')}\` |`,
        );
      }
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

const args = parseArgs(process.argv.slice(2));
const report = JSON.parse(readFileSync(args.in ?? 'reports/mutation/mutation.json', 'utf8'));
const markdown = renderMarkdown(summarise(report), {
  title: args.title ?? 'Mutation baseline — `src/core`',
  scope: args.scope ?? 'src/core/**/*.js',
});
if (args.out) {
  mkdirSync(dirname(args.out), { recursive: true });
  writeFileSync(args.out, markdown);
  process.stdout.write(`Wrote ${args.out}\n`);
} else {
  process.stdout.write(markdown);
}
